"""
LipForensics — Lip-sync Deepfake Detector
Focuses on the mouth region across temporal frames.
Deepfakes generated by lip-sync methods (e.g., Wav2Lip) produce
unnatural mouth movements that differ from genuine speech patterns.

Architecture:
  Mouth ROI Extractor → 3D ResNet (spatiotemporal) → Classifier
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import cv2
from typing import List, Dict, Optional, Tuple


# ---------------------------------------------------------------------------
# Mouth ROI Extractor
# ---------------------------------------------------------------------------

class MouthROIExtractor:
    """
    Extracts the mouth region from a face image using landmark ratios.
    Without a full landmark detector, uses the lower-third of the face
    as a heuristic (works well for aligned/cropped faces).
    """

    # Relative to face crop height/width
    MOUTH_TOP_RATIO    = 0.55
    MOUTH_BOTTOM_RATIO = 0.85
    MOUTH_LEFT_RATIO   = 0.20
    MOUTH_RIGHT_RATIO  = 0.80

    MOUTH_SIZE = (88, 88)  # Standard LipForensics input

    def extract(self, face_crop: np.ndarray) -> np.ndarray:
        """
        face_crop: (H, W, 3) BGR aligned face
        returns:   (88, 88, 3) BGR mouth region
        """
        h, w = face_crop.shape[:2]

        top    = int(h * self.MOUTH_TOP_RATIO)
        bottom = int(h * self.MOUTH_BOTTOM_RATIO)
        left   = int(w * self.MOUTH_LEFT_RATIO)
        right  = int(w * self.MOUTH_RIGHT_RATIO)

        mouth = face_crop[top:bottom, left:right]
        mouth = cv2.resize(mouth, self.MOUTH_SIZE)
        return mouth

    def extract_sequence(self, face_crops: List[np.ndarray]) -> np.ndarray:
        """
        Extract mouth regions from a sequence of face crops.
        Returns: (T, 88, 88, 3)
        """
        mouths = [self.extract(f) for f in face_crops]
        return np.stack(mouths, axis=0)


# ---------------------------------------------------------------------------
# 3D ResNet Block (spatiotemporal convolutions)
# ---------------------------------------------------------------------------

class SpatioTemporalBlock(nn.Module):
    """
    Residual block with 3D convolutions for spatiotemporal processing.
    Captures both spatial (per-frame) and temporal (across frames) features.
    """

    def __init__(self, in_channels: int, out_channels: int, stride: int = 1):
        super().__init__()
        self.conv1 = nn.Conv3d(
            in_channels, out_channels,
            kernel_size=(3, 3, 3), stride=(1, stride, stride),
            padding=1, bias=False
        )
        self.bn1   = nn.BatchNorm3d(out_channels)
        self.conv2 = nn.Conv3d(
            out_channels, out_channels,
            kernel_size=(3, 3, 3), stride=1,
            padding=1, bias=False
        )
        self.bn2   = nn.BatchNorm3d(out_channels)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv3d(in_channels, out_channels, 1, stride=(1, stride, stride), bias=False),
                nn.BatchNorm3d(out_channels),
            )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        return F.relu(out)


class LipForensicsNet(nn.Module):
    """
    3D ResNet for lip-sync deepfake detection.

    Input:  (B, C=3, T, H=88, W=88) — sequence of mouth crops
    Output: (B,) — fake probability
    """

    def __init__(self):
        super().__init__()

        # Initial spatiotemporal conv
        self.stem = nn.Sequential(
            nn.Conv3d(3, 64, kernel_size=(5, 7, 7), stride=(1, 2, 2), padding=(2, 3, 3), bias=False),
            nn.BatchNorm3d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool3d(kernel_size=(1, 3, 3), stride=(1, 2, 2), padding=(0, 1, 1)),
        )

        # Spatiotemporal residual blocks
        self.layer1 = self._make_layer(64,  128, stride=2)
        self.layer2 = self._make_layer(128, 256, stride=2)
        self.layer3 = self._make_layer(256, 512, stride=2)

        self.global_pool = nn.AdaptiveAvgPool3d(1)

        # Temporal attention — weight frames by importance
        self.temporal_attn = nn.Sequential(
            nn.Linear(512, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid(),
        )

        # Classifier
        self.classifier = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(512, 128),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1),
        )

    def _make_layer(self, in_channels: int, out_channels: int, stride: int) -> nn.Sequential:
        return nn.Sequential(
            SpatioTemporalBlock(in_channels, out_channels, stride=stride),
            SpatioTemporalBlock(out_channels, out_channels, stride=1),
        )

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        x: (B, 3, T, 88, 88)
        Returns: (fake_prob (B,), features (B, 512))
        """
        out  = self.stem(x)
        out  = self.layer1(out)
        out  = self.layer2(out)
        out  = self.layer3(out)
        out  = self.global_pool(out).flatten(1)  # (B, 512)

        logit    = self.classifier(out)
        fake_prob = torch.sigmoid(logit).squeeze(-1)
        return fake_prob, out


# ---------------------------------------------------------------------------
# Inference wrapper
# ---------------------------------------------------------------------------

class LipForensicsInference:
    """
    Runs LipForensics on extracted face crops from a video.
    Specifically targets lip-sync deepfakes.
    """

    SEQUENCE_LENGTH = 25  # ~1 second at 25fps

    def __init__(self, model_path: Optional[str] = None, device: str = "cpu"):
        self.device     = torch.device(device)
        self.model      = LipForensicsNet().to(self.device)
        self.extractor  = MouthROIExtractor()

        if model_path:
            ckpt = torch.load(model_path, map_location=self.device)
            self.model.load_state_dict(ckpt["model_state_dict"])

        self.model.eval()

    @torch.no_grad()
    def predict_frames(self, face_crops: List[np.ndarray]) -> Dict:
        """
        face_crops: list of aligned face crops (BGR, 224x224)
        """
        if len(face_crops) < self.SEQUENCE_LENGTH:
            # Pad by repeating last frame
            while len(face_crops) < self.SEQUENCE_LENGTH:
                face_crops.append(face_crops[-1])

        clip_probs = []

        for start in range(0, len(face_crops) - self.SEQUENCE_LENGTH + 1, self.SEQUENCE_LENGTH // 2):
            clip       = face_crops[start: start + self.SEQUENCE_LENGTH]
            mouth_seq  = self.extractor.extract_sequence(clip)   # (T, 88, 88, 3)
            tensor     = self._preprocess_mouth_seq(mouth_seq)    # (1, 3, T, 88, 88)
            tensor     = tensor.to(self.device)

            fake_prob, _ = self.model(tensor)
            clip_probs.append(float(fake_prob.cpu().item()))

        if not clip_probs:
            return {"error": "Not enough frames"}

        final_prob = float(np.mean(clip_probs))

        return {
            "fake_probability":    round(final_prob, 4),
            "real_probability":    round(1 - final_prob, 4),
            "is_fake":             final_prob > 0.5,
            "verdict":             "FAKE" if final_prob > 0.5 else "REAL",
            "method":              "LipForensics",
            "focus":               "Lip-sync temporal consistency",
            "clips_analyzed":      len(clip_probs),
            "clip_probs":          [round(p, 4) for p in clip_probs],
        }

    def _preprocess_mouth_seq(self, mouth_seq: np.ndarray) -> torch.Tensor:
        """
        mouth_seq: (T, 88, 88, 3) uint8 BGR
        returns:   (1, 3, T, 88, 88) float normalized
        """
        MEAN = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1, 1)
        STD  = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1, 1)

        # BGR → RGB, normalize
        seq_rgb  = mouth_seq[:, :, :, ::-1].copy()          # (T, 88, 88, 3)
        tensor   = torch.from_numpy(seq_rgb).float() / 255.0 # (T, 88, 88, 3)
        tensor   = tensor.permute(3, 0, 1, 2)               # (3, T, 88, 88)
        tensor   = (tensor - MEAN) / STD
        return tensor.unsqueeze(0)                           # (1, 3, T, 88, 88)
